name: Vercel Preview Deployment
on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Create Supabase config
        run: |
          mkdir -p supabase
          echo "project_id = \"iprryfxddcybfmbjgiby\"" > supabase/config.toml
          echo "[api]" >> supabase/config.toml
          echo "port = 54321" >> supabase/config.toml

      - name: Install Dependencies
        run: |
          git config --global core.autocrlf false
          git config --global core.safecrlf false
          npm ci --no-audit --ignore-scripts

      # Set environment variables
      - name: Set Environment Variables
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV

      # Handle Supabase types
      - name: Setup Supabase Types
        run: |
          # Create directory and placeholder file
          mkdir -p lib/services/supabase/types
          cat > lib/services/supabase/types/index.ts << EOL
          // Generated types - placeholder for build
          export type Database = {
            public: {
              Tables: Record<string, any>
              Views: Record<string, any>
              Functions: Record<string, any>
            }
          }
          EOL
          
          # Stage the types file to prevent Git errors
          git add lib/services/supabase/types/index.ts
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "chore: add placeholder types for build" --no-verify

      - name: Run Lint
        run: npm run lint

      - name: Run Type Check
        run: npm run typecheck
        
      - name: Build Project
        run: |
          # Temporarily disable Husky
          HUSKY=0 CI=true npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SKIP_ENV_VALIDATION: true
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./