name: Vercel Preview Deployment
on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Create Supabase config
        run: |
          mkdir -p supabase
          echo 'project_id = "${{ vars.SUPABASE_PROJECT_ID }}"' > supabase/config.toml
          echo 'org_id = "${{ vars.SUPABASE_ORG_ID }}"' >> supabase/config.toml

      - name: Install Dependencies
        run: npm ci
        
      - name: Build Project
        run: |
          # Clean build directories
          rm -rf .next out

          # Create necessary directories
          mkdir -p lib/services/supabase/types
          touch lib/services/supabase/types/.gitkeep

          # Run build
          npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./